import type { MacroCategoryId, MacroTemplate } from "@/types/macro";

const FONT_FAMILY = `font-family: {{fontFamily}}, sans-serif !important;`;
const TEXT_DECORATION_NONE = "text-decoration: none;";

export const macroCategoryLabels: Record<MacroCategoryId, string> = {
  basic: "기본",
  roll: "판정·주사위",
  info: "정보",
  decorate: "강조",
  scene: "장면",
  custom: "사용자",
};

export const macroCategoryOrder: MacroTemplate["categoryId"][] = [
  "basic",
  "roll",
  "info",
  "decorate",
  "scene",
];

export const macroTemplates: MacroTemplate[] = [
  {
    id: "narration",
    categoryId: "basic",
    order: 1,
    name: "나레이션",
    memo: "글꼴과 텍스트 스타일을 조절하는 기본 묘사",
    previewText: "내용을 입력하세요",
    keywords: ["나레이션", "묘사", "desc", "글꼴"],
    platform: "roll20",
    previewKind: "narration",
    code: `/desc [{{content}}](#" style="${FONT_FAMILY} ${TEXT_DECORATION_NONE} color: {{textColor}}; font-weight: {{fontWeight}}; font-style: {{fontStyle}};")`,
    fields: [
      {
        key: "fontFamily",
        label: "글꼴",
        type: "text",
        defaultValue: "Pretendard",
      },
      {
        key: "textColor",
        label: "글자색",
        type: "color",
        defaultValue: "#333333",
      },
      {
        key: "fontWeight",
        label: "굵기",
        type: "select",
        defaultValue: "normal",
        options: [
          { label: "보통", value: "normal" },
          { label: "굵게", value: "bold" },
        ],
      },
      {
        key: "fontStyle",
        label: "기울임",
        type: "select",
        defaultValue: "normal",
        options: [
          { label: "사용 안 함", value: "normal" },
          { label: "기울임", value: "italic" },
        ],
      },
    ],
  },
  {
    id: "npc-speech",
    categoryId: "basic",
    order: 2,
    name: "NPC 대사",
    memo: "NPC 이름으로 대사를 출력",
    previewText: "NPC가 대사를 말합니다",
    keywords: ["NPC", "대사", "as"],
    platform: "roll20",
    previewKind: "speech",
    code: `/as "{{speaker}}" {{content}}`,
    fields: [
      {
        key: "speaker",
        label: "NPC 이름",
        type: "text",
        defaultValue: "NPC",
      },
    ],
  },
  {
    id: "roll-basic",
    categoryId: "roll",
    order: 1,
    name: "기본 주사위",
    memo: "원하는 면수의 공개 주사위를 굴림",
    previewText: "1d100",
    keywords: ["주사위", "판정", "roll", "다이스"],
    platform: "roll20",
    previewKind: "dice",
    code: `/r 1d{{diceSides}}`,
    fields: [
      {
        key: "diceSides",
        label: "주사위 면수",
        type: "text",
        defaultValue: "100",
      },
    ],
  },
  {
    id: "judgement-button",
    categoryId: "roll",
    order: 2,
    name: "판정 버튼",
    memo: "기능명과 그라데이션을 설정하는 판정 표시",
    previewText: "✷ 기능 판정 ✷",
    keywords: ["판정", "버튼", "기능", "그라데이션"],
    platform: "roll20",
    previewKind: "judgement",
    code: `/desc [　✷　{{content}} 판정　✷　](#" style="font-family: Pretendard, sans-serif !important; ${TEXT_DECORATION_NONE} font-style: normal; text-align: center; display: inline-block; color: white; border-radius: 20px; padding: 5px 15px; background-image: linear-gradient(135deg&#44; {{gradientStart}}&#44; {{gradientEnd}}&#41;;")`,
    fields: [
      {
        key: "gradientStart",
        label: "시작 색상",
        type: "color",
        defaultValue: "#FF0053",
      },
      {
        key: "gradientEnd",
        label: "끝 색상",
        type: "color",
        defaultValue: "#FFD444",
      },
    ],
  },
  {
    id: "thin-text-two-lines",
    categoryId: "info",
    order: 1,
    name: "얇은 글씨 두 줄",
    memo: "캐치프레이즈와 설명을 두 줄로 출력",
    previewText: "첫 번째 줄",
    keywords: ["얇은 글씨", "두 줄", "캐치프레이즈"],
    platform: "roll20",
    previewKind: "thin-two-lines",
    code: `/desc [{{content}}](#" style="font-family: Pretendard, sans-serif !important; ${TEXT_DECORATION_NONE} color: {{textColor}}; font-size: 12px; font-weight: normal;") [{{secondLine}}](#" style="font-family: Pretendard, sans-serif !important; ${TEXT_DECORATION_NONE} color: {{textColor}}; display: block; font-size: 12px; font-weight: normal;")`,
    fields: [
      {
        key: "secondLine",
        label: "두 번째 줄",
        type: "text",
        defaultValue: "두 번째 줄",
      },
      {
        key: "textColor",
        label: "글자색",
        type: "color",
        defaultValue: "#333333",
      },
    ],
  },
  {
    id: "thin-text-one-line",
    categoryId: "info",
    order: 2,
    name: "얇은 글씨 한 줄",
    memo: "작은 크기의 얇은 글씨를 한 줄로 출력",
    previewText: "얇은 글씨",
    keywords: ["얇은 글씨", "한 줄"],
    platform: "roll20",
    previewKind: "thin-one-line",
    code: `/desc [{{content}}](#" style="font-family: Pretendard, sans-serif !important; ${TEXT_DECORATION_NONE} color: {{textColor}}; font-size: 12px; font-weight: normal;")`,
    fields: [
      {
        key: "textColor",
        label: "글자색",
        type: "color",
        defaultValue: "#333333",
      },
    ],
  },
  {
    id: "kpc-pc",
    categoryId: "info",
    order: 3,
    name: "KPC / PC 표시",
    memo: "KPC와 PC 이름을 함께 표시",
    previewText: "KPC / PC",
    keywords: ["KPC", "PC", "이름"],
    platform: "roll20",
    previewKind: "kpc-pc",
    code: `/desc [KPC](#" style="font-family: Pretendard, sans-serif !important; ${TEXT_DECORATION_NONE} color: {{accentColor}};") [{{kpcName}}](#" style="font-family: Pretendard, sans-serif !important; ${TEXT_DECORATION_NONE} color: #333333;")　[PC](#" style="font-family: Pretendard, sans-serif !important; ${TEXT_DECORATION_NONE} color: {{accentColor}};") [{{pcName}}](#" style="font-family: Pretendard, sans-serif !important; ${TEXT_DECORATION_NONE} color: #333333;")`,
    fields: [
      { key: "kpcName", label: "KPC 이름", type: "text", defaultValue: "KPC" },
      { key: "pcName", label: "PC 이름", type: "text", defaultValue: "PC" },
      {
        key: "accentColor",
        label: "강조색",
        type: "color",
        defaultValue: "#FF0053",
      },
    ],
  },
  {
    id: "writer",
    categoryId: "info",
    order: 4,
    name: "라이터",
    memo: "시나리오 작성자를 표시",
    previewText: "작성자 이름",
    keywords: ["라이터", "작가", "written"],
    platform: "roll20",
    previewKind: "writer",
    code: `/desc [Written by](#" style="font-family: Pretendard, sans-serif !important; ${TEXT_DECORATION_NONE} color: {{accentColor}};") [{{content}}](#" style="font-family: Pretendard, sans-serif !important; ${TEXT_DECORATION_NONE} color: #333333;")`,
    fields: [
      {
        key: "accentColor",
        label: "강조색",
        type: "color",
        defaultValue: "#FF0053",
      },
    ],
  },
  {
    id: "background-highlight",
    categoryId: "decorate",
    order: 1,
    name: "배경 강조",
    memo: "글자색과 배경색을 지정하는 강조 블록",
    previewText: "강조할 내용",
    keywords: ["배경", "강조", "색상"],
    platform: "roll20",
    previewKind: "background-highlight",
    code: `/desc [{{content}}](#" style="font-family: Pretendard, sans-serif !important; ${TEXT_DECORATION_NONE} color: {{textColor}}; background-color: {{backgroundColor}}; text-align: center; display: block; padding: 4px; line-height: 1.3;")`,
    fields: [
      {
        key: "textColor",
        label: "글자색",
        type: "color",
        defaultValue: "#ffffff",
      },
      {
        key: "backgroundColor",
        label: "배경색",
        type: "color",
        defaultValue: "#B9062F",
      },
    ],
  },
  {
    id: "blur",
    categoryId: "decorate",
    order: 2,
    name: "블러 처리",
    memo: "검은 그림자로 내용을 가림",
    previewText: "가릴 내용",
    keywords: ["블러", "스포일러", "비밀", "가리기"],
    platform: "roll20",
    previewKind: "blur",
    code: `[{{content}}](#" style="${TEXT_DECORATION_NONE} color: rgba(0&#44;0&#44;0&#44;0&#41;; text-shadow: 5px 0 10px black&#44; -5px 0 10px black; font-size: {{fontSize}};")`,
    fields: [
      {
        key: "fontSize",
        label: "글자 크기",
        type: "text",
        defaultValue: "11px",
      },
    ],
  },
  {
    id: "divider",
    categoryId: "scene",
    order: 1,
    name: "가름선",
    memo: "장면 전환용 선과 장식을 표시",
    previewText: "──── ✷ ────",
    keywords: ["가름선", "구분선", "장면", "전환"],
    platform: "roll20",
    previewKind: "divider",
    code: `/desc [{{divider}}](#" style="font-family: Pretendard, sans-serif !important; ${TEXT_DECORATION_NONE} color: {{lineColor}};") [{{ornament}}](#" style="font-family: Pretendard, sans-serif !important; ${TEXT_DECORATION_NONE} color: {{ornamentColor}};") [{{divider}}](#" style="font-family: Pretendard, sans-serif !important; ${TEXT_DECORATION_NONE} color: {{lineColor}};")`,
    fields: [
      {
        key: "divider",
        label: "구분선",
        type: "text",
        defaultValue: "───────",
      },
      { key: "ornament", label: "장식", type: "text", defaultValue: "✷" },
      {
        key: "lineColor",
        label: "선 색상",
        type: "color",
        defaultValue: "#333333",
      },
      {
        key: "ornamentColor",
        label: "장식 색상",
        type: "color",
        defaultValue: "#FF0053",
      },
    ],
  },
];
